version: '3.8'

services:
  adam-cv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-service
    ports:
      - "7860:7860"
    env_file: .env
    command: ["python", "src/user_interface.py"]