version: '3.8'

services: 
  adam-cv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adamcv
    ports:
      - "7860:7860"
    env_file: .env

  # kernel_memory:
  #   image: kernelmemory/service
  #   container_name: kernelmemoryadamCV
  #   volumes:
  #     - ./appsettings.Development.json:/app/appsettings.Production.json

  #   restart: unless-stopped