version: '3.8'

services: 
  adam-cv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adamcv
    ports:
      - "7860:7860"
    env_file: .env
    command: ["python", "user_interface.py"]

  kernel_memory:
    image: kernelmemory/service
    container_name: kernelmemoryadamCV
    restart: unless-stopped
    